### ISSUE TITLE
코드 리뷰

### ISSUE THREAD

**Issue by lsmman** [JihyeChu/Blog_login_signup#1]
ist<FieldError> fieldErrors = bindingResult.getFieldErrors();
        if(fieldErrors.size() > 0) {
            for (FieldError fieldError : bindingResult.getFieldErrors()) {
                log.error(fieldError.getField() + " 필드 : " + fieldError.getDefaultMessage());
            }
            return;
        }

바인드 에러 처리를 이런식으로 하는 것보다 BindExcpetion을 받아 처리하는 ExceptionHandler를 선언해서 만들어보시면 좋겠습니다.

**Comment by lsmman** [comment]
해주신 것처럼 적절한 Optional 사용은 메소드의 다중화를 막아줍니다.

```
Optional<User> findByUsername(String username);
```

**Comment by lsmman** [comment]
총평 코드에 기본적ㅇ로 감각이 있는 것이 보입니다.
자잘한 에러 외에는 너무나 잘해주셨고, 감사합니다.

**Comment by JihyeChu** [comment]
넵.  ExceptionHandler를 선언해서 에러 처리해보겠습니다. 감사합니다.
